version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:2.8.1
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor

    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@airflow-metadata-db:5432/${POSTGRES_DB}

    AIRFLOW__CELERY__BROKER_URL: redis://airflow-redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@airflow-metadata-db:5432/${POSTGRES_DB}

  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins

  depends_on:
    airflow-metadata-db:
      condition: service_healthy
    redis:
      condition: service_started

services:

  # ---------- Airflow metadata database ----------
  airflow-metadata-db:
    image: postgres:15
    container_name: airflow-metadata-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    volumes:
      - airflow_metadata_db:/var/lib/postgresql/data

  # ---------- Redis ----------
  redis:
    image: redis:7
    container_name: airflow-redis
    ports:
      - "6379:6379"

  # ---------- Airflow DB Init ----------
  airflow-init:
   image: apache/airflow:2.8.1
   env_file:
    - .env
   environment:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@airflow-metadata-db:5432/${POSTGRES_DB}
   command: >
    bash -c "
    airflow db init &&
    airflow users create --username airflow --password airflow --firstname Airflow --lastname Admin --role Admin --email airflow@example.com
    "
   depends_on:
    airflow-metadata-db:
      condition: service_healthy


  # ---------- Airflow services ----------
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler

  airflow-worker:
    <<: *airflow-common
    container_name: airflow-worker
    command: celery worker

  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow-triggerer
    command: triggerer

  # ---------- Local target Postgres ----------
  local-postgres:
    image: postgres:15
    container_name: local-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${LOCAL_PG_USER}
      POSTGRES_PASSWORD: ${LOCAL_PG_PASSWORD}
      POSTGRES_DB: ${LOCAL_PG_DB}
    ports:
      - "5433:5432"
    volumes:
      - local_pg_data:/var/lib/postgresql/data

volumes:
  airflow_metadata_db:
  local_pg_data:
